### ISSUE TITLE
Debian Install complains about missing get_client_uuid/set_client_uuid

### ISSUE THREAD

**Issue by arlake228** [perfsonar/ls-registration-daemon#11]
When upgrading the ls-registration-daemon on debian I get the following: 

Setting up perfsonar-lsregistrationdaemon (3.5~4.rc2-1) ...
"get_client_uuid" is not exported by the perfSONAR_PS::Utils::LookupService module
 "set_client_uuid" is not exported by the perfSONAR_PS::Utils::LookupService module
Can't continue after import errors at /usr/lib/perfsonar/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Base.pm line 27
BEGIN failed--compilation aborted at /usr/lib/perfsonar/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Base.pm line 27.
Compilation failed in require at (eval 44) line 2.
	...propagated at /usr/share/perl/5.14/base.pm line 93.
BEGIN failed--compilation aborted at /usr/lib/perfsonar/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Person.pm line 6.
Compilation failed in require at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 25.
BEGIN failed--compilation aborted at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 25.

Looks like maybe the code from perl-shared needs to be updated?

**Comment by tonin** [comment]
Is this error on the same server as for https://github.com/perfsonar/mesh-config/issues/18 ?  What is the version of `libperfsonar-perl` here?  Which perfsonar-debian repositories are activated in `/etc/apt/sources.list.d/` ?

**Comment by arlake228** [comment]
I fixed this. I did a manual upgrade yesterday but didn't notice that it held libperfsonar back. I ran `apt-get dist-upgrade` and it installed the proper version. Same deal for perfsonar/mesh-config#18. Sorry to have bothered you with this.
