### ISSUE TITLE
ls_registration does not verify interface assignments

### ISSUE THREAD

**Issue by igarny** [perfsonar/ls-registration-daemon#12]
In GEANT we are using multiple interfaces on our hosts. We are registering the specific services to designated interfaces.
The problem is that despite one interface is down the ls_registration_daemon continues to report the service and registration as up.
I have produced that on the testbed perfSONAR 3.5-rc2 (in staging repository) instance with CentOS 6.7. 
perl-perfSONAR_PS-LSRegistrationDaemon-3.5-0.5.rc2.pSPS.noarch

/opt/perfsonar_ps/ls_registration_daemon/etc/ls_registration_daemon.conf:
`country   DE`
`city   Erlangen`
`<administrator>`
`    email   ivan.garnizov@fau.de`
`    name   Ivan Garnizov`
`</administrator>`
`<service_template>`
`    <local_latency_service>`
`        primary_interface        eth0`
`        autodiscover_addresses   1`
`    </local_latency_service>`
`    <local_bandwidth_service>`
`        primary_interface        eth1`
`        autodiscover_addresses   1`
`    </local_bandwidth_service>`
`    <local_web_service>`
`        primary_interface        eth0`
`        autodiscover_addresses   1`
`    </local_web_service>`
`</service_template>`
`<site host>`
`    autodiscover   1`
`    autodiscover_interfaces   1`
`    <service>`
`        inherits   local_latency_service`
`        type   ping`
`    </service>`
`    <service>`
`        inherits   local_latency_service`
`        type   traceroute`
`    </service>`
`    <service>`
`        inherits   local_latency_service`
`        type   owamp`
`    </service>`
`    <service>`
`        inherits   local_bandwidth_service`
`        type   bwctl`
`    </service>`
`    <service>`
`        inherits   local_bandwidth_service`
`        type   ndt`
`    </service>`
`    <service>`
`        inherits   local_bandwidth_service`
`        type   npad`
`    </service>`
`    <service>`
`        url_path   /esmond/perfsonar/archive`
`        autodiscover_tests   1`
`        inherits   local_web_service`
`        http_port   80`
`        type   ma`
`        service_version   esmond-1.0`
`        https_port   443`
`    </service>`
`    <service>`
`        url_path   /services/MP/BWCTL`
`        inherits   local_bandwidth_service`
`        http_port   8090`
`        type   mp_bwctl`
`        service_version   oppd-3.4`
`        https_port   443`
`    </service>`
`    <service>`
`        url_path   /services/MP/OWAMP`
`        inherits   local_latency_service`
`        http_port   8090`
`        type   mp_owamp`
`        service_version   oppd-3.4`
`        https_port   443`
`    </service>`
`    is_local   1`
`</site>`
`check_interval   3600`
`allow_internal_addresses   0`
`site_name   RRZE`

I have had the eth1 interface down and in logs:
2015/09/24 15:16:05 (24967) INFO> Base.pm:260 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is up, refreshing registration (key=lookup/interface/0a4a0a6c-9ff0-452d-8afb-963e9fa1b399, description=eth1)
2015/09/24 15:16:06 (24967) INFO> Base.pm:332 perfSONAR_PS::LSRegistrationDaemon::Base::keepalive - Service renewed. Next Refresh: 1443104165(key=lookup/interface/0a4a0a6c-9ff0-452d-8afb-963e9fa1b399, description=eth1)

2015/09/24 15:16:08 (24967) INFO> Base.pm:260 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is up, refreshing registration (key=lookup/service/322f8758-58a6-4c2f-b4f6-75f5fd925d94, description=RRZE BWCTL Server)
2015/09/24 15:16:09 (24967) INFO> Base.pm:332 perfSONAR_PS::LSRegistrationDaemon::Base::keepalive - Service renewed. Next Refresh: 1443104169(key=lookup/service/322f8758-58a6-4c2f-b4f6-75f5fd925d94, description=RRZE BWCTL Server)
2015/09/24 15:16:09 (24967) WARN> daemon.pl:240 main::__ANON__ - Warned: Use of uninitialized value in concatenation (.) or string at /opt/perfsonar_ps/ls_registration_daemon/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Base.pm line 272.
2015/09/24 15:16:09 (24967) INFO> Base.pm:272 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is down (key=, description=RRZE NDT Server)
2015/09/24 15:16:09 (24967) WARN> daemon.pl:240 main::__ANON__ - Warned: Use of uninitialized value in concatenation (.) or string at /opt/perfsonar_ps/ls_registration_daemon/bin/../lib/perfSONAR_PS/LSRegistrationDaemon/Base.pm line 272.
2015/09/24 15:16:09 (24967) INFO> Base.pm:272 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is down (key=, description=RRZE NPAD Server)
2015/09/24 15:16:09 (24967) INFO> Base.pm:260 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is up, refreshing registration (key=lookup/service/a2bd470f-6610-4a91-acec-d326c73423e8, description=RRZE Measurement Archive)

**Comment by arlake228** [comment]
This should be fixed in master of perl-shared. Fixed code that was ignoring down interfaces and that was picking addresses for things without addresses.
