### ISSUE TITLE
add support for registering the type of perfSONAR node into the sLS

### ISSUE THREAD

**Issue by arlake228** [perfsonar/ls-registration-daemon#2]
_From @arlake228 on March 14, 2015 12:50_

Original [issue 1059](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059) created by arlake228 on 2015-01-29T00:24:02.000Z:

ability to register the type of a perfSONAR nodes, such as:
  - NREN
  - regional
  - site border
  - site internal
  - Science DMZ
  - exchange point

register the type of access for a given node. e.g.:
  - public 
  - R&amp;E only
  - private
  - with permission (e.g.: send email to request getting added to ACL)
  - locale site only

This is very easy from a coding writing point of view, but harder to define the right categories, and will require discussion.

_Copied from original issue: perfsonar/project#1057_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c1) originally posted by arlake228 on 2015-01-29T01:03:42.000Z:


additional type: Test host

Also consider added a 'description' or 'notes' field that gets registered too.

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c2) originally posted by arlake228 on 2015-01-30T18:10:24.000Z:

Issue 1066 has been merged into this issue.

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c3) originally posted by arlake228 on 2015-01-30T18:12:54.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#4](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c4) originally posted by arlake228 on 2015-01-30T19:10:26.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#5](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c5) originally posted by arlake228 on 2015-01-30T20:11:52.000Z:


merging issue 1058 into this, as its related:

VMs can have problems with OWAMP, small boxes can have problems with high throughput tests. It'd be good to have some way to flag these limitations and put them into the lookup service, or via BWCTL or what-have-you

**Comment by arlake228** [comment]
Comment [#6](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c6) originally posted by arlake228 on 2015-01-30T20:12:30.000Z:

Issue 1058 has been merged into this issue.

**Comment by arlake228** [comment]
Comment [#7](https://code.google.com/p/perfsonar-ps/issues/detail?id=1059#c7) originally posted by arlake228 on 2015-02-02T14:08:41.000Z:

Issue 905 has been merged into this issue.

**Comment by apertome** [comment]
Once this has been implemented, we can add this information to the toolkit UI.

**Comment by bltierney** [comment]
Michael: Has this been added to the GUI yet?

**Comment by apertome** [comment]
No, does support for this exist somewhere?

**Comment by bltierney** [comment]
Yes, the LS supports it now. Maybe we should discuss at this weeks call.

**Comment by arlake228** [comment]
Yes, it is supported in ls_registration_daemon.conf. You can insert these fields the same way you insert the rest of the admin info. You can use the role option: http://docs.perfsonar.net/3.5rc1/config_ls_registration.html#role-directive

**Comment by apertome** [comment]
Great, yes, let's discuss as this week's call.
