### ISSUE TITLE
"lookup_service_is_active" is not exported by the perfSONAR_PS::Utils::LookupService module

### ISSUE THREAD

**Issue by cpaolini** [perfsonar/ls-registration-daemon#27]
Can't invoke lsregistrationdaemon on CentOS release 6.8 ("lookup_service_is_active" and "lookup_services_latency_diff" not exported by the perfSONAR_PS::Utils::LookupService module):

# /etc/init.d/perfsonar-lsregistrationdaemon start
/usr/lib/perfsonar/bin/lsregistrationdaemon.pl --config=/etc/perfsonar/lsregistrationdaemon.conf --pidfile=/var/run/lsregistrationdaemon.pid --logger=/etc/perfsonar/lsregistrationdaemon-logger.conf --user=perfsonar --group=perfsonar
"lookup_service_is_active" is not exported by the perfSONAR_PS::Utils::LookupService module
 "lookup_services_latency_diff" is not exported by the perfSONAR_PS::Utils::LookupService module
Can't continue after import errors at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 24.
BEGIN failed--compilation aborted at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 24.
/etc/init.d/perfsonar-lsregistrationdaemon start: LS Registration Daemon could not be started
#

**Comment by arlake228** [comment]
See user list this morning. Missing RPM was uploaded that will correct this.

**Comment by cpaolini** [comment]
Thanks Andrew.  I just got the update:

================================================================================
 Package                            Arch     Version          Repository
 Size
================================================================================
Updating:
 libperfsonar-esmond-perl           noarch   3.5.1.9-1.el6    Internet2
 libperfsonar-perl                  noarch   3.5.1.9-1.el6    Internet2
 libperfsonar-regulartesting-perl   noarch   3.5.1.9-1.el6    Internet2
 libperfsonar-sls-perl              noarch   3.5.1.9-1.el6    Internet2
 libperfsonar-toolkit-perl          noarch   3.5.1.9-1.el6    Internet2

Best,

Chris
