### ISSUE TITLE
ERROR> lsregistrationdaemon.pl:152 main::__ANON__ - Died: Insecure dependency in system while running with -T switch at /usr/share/perl5/vendor_perl/Net/Ping/External.pm line 105.

### ISSUE THREAD

**Issue by soichih** [perfsonar/ls-registration-daemon#29]
I am trying to install a brand new instance of perfSONAR toolkit on a Jetstream VM by looking at http://docs.perfsonar.net/install_centos.html

I've used a public CentOS6 image available for IU Jetstream datacenter, and I believe I was able to install the toolkit instance successfully. I've given it a public ip/hostname (https://ps.soichi.us/toolkit/) and I was able to configure my tookit via web UI.

Now, I am trying to make it registered to global LS. All Jetstream VM uses DHCP, and static IP (floating-ip) is accomplished via NAT-ing. So my VM doesn't have the public IP address associated to its interface.. Like..
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast state UP qlen 10000
    link/ether fa:16:3e:71:ec:30 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.24/24 brd 10.0.0.255 scope global eth0
    inet6 fe80::f816:3eff:fe71:ec30/64 scope link 
       valid_lft forever preferred_lft forever
```

So, to have the service-locator populated with my public IP on global LS, I've edited /etc/perfsonar/lsregistrationdaemon.conf with following content.

```
## Administrative domain of host in DNS format
domain ps.soichi.us

#attempt to set service-locator with correct IP address (doesn't work?)
address ps.soichi.us
```

I don't know if this will work or not.. By the way, I've ignore Step 6 of this doc - which seems to be obsolete.
> http://docs.perfsonar.net/install_centos.html

I then restarted my VM.

I am seeing following on /var/log/perfsonar/lsregistrationdaemon.log

```
2017/01/16 14:13:42 (2217) INFO> lsregistrationdaemon.pl:257 main:: - Initial LS URL set to http://ps-east.es.net:8090/lookup/records
2017/01/16 14:13:43 (2234) INFO> Base.pm:128 perfSONAR_PS::LSRegistrationDaemon::Base::init - Changes in record, will delete lookup/host/64887acb-f162-4345-a3e6-4528b22d6ed1
2017/01/16 14:13:46 (2234) INFO> Base.pm:257 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record is up, registering (description=)
2017/01/16 14:13:46 (2234) INFO> Base.pm:309 perfSONAR_PS::LSRegistrationDaemon::Base::register - Service registered. Next Refresh: 1484597626(key=lookup/host/2dac0348-53ab-4616-90c4-ae019708cd74, description=)
2017/01/16 14:13:46 (2234) ERROR> lsregistrationdaemon.pl:152 main::__ANON__ - Died: Insecure dependency in system while running with -T switch at /usr/share/perl5/vendor_perl/Net/Ping/External.pm line 105.
```

I only see my host record registered on http://ps-east.es.net:8090/lookup/records (no service records). 

Can you help me troubleshoot this problem?

**Comment by arlake228** [comment]
Looks like this was fixed is more recent code tree it just was not backported to 3.5. Grabbing the latest from staging should resolve it.
