### ISSUE TITLE
Problem with registration in a fresh host

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/ls-registration-daemon#35]
After fresh installation of 3.5.1 (testpoint bundle) host refuses to register to LS and stops working. Here is the log after daemon restart:

[root@tor-m perfsonar]# cat /var/log/perfsonar/lsregistrationdaemon.log
2017/02/13 10:51:21 (29382) WARN> lsregistrationdaemon.pl:144 main::__ANON__ - Warned: Use of uninitialized value $current_ls_instance in concatenation (.) or string at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 257.
2017/02/13 10:51:21 (29382) INFO> lsregistrationdaemon.pl:257 main:: - Initial LS URL set to
2017/02/13 10:51:21 (29382) ERROR> lsregistrationdaemon.pl:301 main:: - Unable to determine ls_instance so not performing any operations
2017/02/13 11:28:48 (3352) WARN> lsregistrationdaemon.pl:144 main::__ANON__ - Warned: Use of uninitialized value $current_ls_instance in concatenation (.) or string at /usr/lib/perfsonar/bin/lsregistrationdaemon.pl line 257.
2017/02/13 11:28:48 (3352) INFO> lsregistrationdaemon.pl:257 main:: - Initial LS URL set to
2017/02/13 11:28:48 (3352) ERROR> lsregistrationdaemon.pl:301 main:: - Unable to determine ls_instance so not performing any operations
[root@tor-m perfsonar]#

[root@tor-m perfsonar]# rpm -qa|grep lsre
perfsonar-lsregistrationdaemon-3.5.1.8-1.el6.noarch
[root@tor-m perfsonar]#

And the log message is truncated "Initial LS URL set to"....

**Comment by bltierney** [comment]
do we still see this? Maybe it can be closed?

**Comment by arlake228** [comment]
This was fixed awhile back as part of overhaul related to 4.0 changes. The root of the problem is likely no external network connectivity to the LSes, so crashing isn't changing the net result, though the old code could have thrown a nicer error message.
