### ISSUE TITLE
UTF-8 issue with location-sitename field

### ISSUE THREAD

**Issue by tonin** [perfsonar/ls-registration-daemon#36]
I have a CentOS 6 host that is using UTF-8 chars in the name of the Organisation (GÉANT).

That is displayed fine in the Toolkit web gui: http://ps-c6.eshango.net/toolkit/ but not in the LS information registered in the `location-sitename` field at http://ps-east.es.net:8090/lookup/host/4b29cd52-5ea7-423e-b8ed-96eb7b663704  The info from ps-east.es.net is then used in Service Directory and is also displayed wrongly **GÃANT**

**Comment by vvidic** [comment]
Antoine, can you check it this patch works on your host?

Note you will have to force Unicode/UTF8 encoding in the browser when viewing the LS page as it doesn't send any encoding info with the data.

**Comment by tonin** [comment]
Yes, it looks good in the LS pages both from an Ubuntu 14 and a CentOS 6 host.  I guess it will show up fine on the Service Directory too.

**Comment by vvidic** [comment]
Created pull request #37 for Andy to check.
