### ISSUE TITLE
documentation misses: configuration file check + clatency threshold

### ISSUE THREAD

**Issue by igarny** [perfsonar/ls-registration-daemon#41]
2017/05/08 09:31:33 (28160) INFO> lsregistrationdaemon.pl:312 main:: - Configuration file change detected, refreshing records.
2017/05/08 09:31:33 (28160) DEBUG> lsregistrationdaemon.pl:194 main:: - No configuration file check interval specified. Defaulting to 60 seconds
2017/05/08 09:31:33 (28160) DEBUG> lsregistrationdaemon.pl:200 main:: - No clatency threshold specified for switching LSes. Defaulting to 10%

**Comment by arlake228** [comment]
For my own reference, the first refers to `check_config_interval` and the second (btw clatency is likely a typo) maps to the `s_instance_latency_threshold`. Neither of these options should be touched by the average user, though they should be documented.
