### ISSUE TITLE
Add CPU architecture to the LS registration

### ISSUE THREAD

**Issue by tonin** [perfsonar/ls-registration-daemon#42]
It looks like some Debian or Ubuntu host are not reporting the correct CPU architecture they're running.  In the LS listings, we found a lot of registrations like the following:

```
  0-4-amd64                                             31     1.56 %
  4-amd64                                               25     1.26 %
  unknown                                                6      0.3 %
  24-v7+                                                 5     0.25 %
  0-32-generic                                           4      0.2 %
  0-75-generic                                           2      0.1 %
  0-78-generic                                           2      0.1 %
  0-21-generic                                           2      0.1 %
  35-web100triumvirs                                     2      0.1 %
  2-amd64                                                2      0.1 %
  112-bananian                                           2      0.1 %
  0-77-generic                                           2      0.1 %
  0-42-generic                                           2      0.1 %
  0-72-generic                                           1     0.05 %
  0-4-686-pae                                            1     0.05 %
  0-29-generic                                           1     0.05 %
  65-75                                                  1     0.05 %
  26-v7+                                                 1     0.05 %
  32-5-686                                               1     0.05 %
  32-18-pve                                              1     0.05 %
  48-guest-8-a3e3ebf-x86_64                              1     0.05 %
  8                                                      1     0.05 %
  0-66-generic                                           1     0.05 %
  38-v7+                                                 1     0.05 %
  0-31-generic                                           1     0.05 %
  0-47-generic                                           1     0.05 %
  85-xenU-26-081911a-x86_64                              1     0.05 %
```

These look like Debian/Ubuntu kernel suffixes and are most probably due to bad parsing of the `uname` output or something similar.  We should double check that.

It turns out that the CPU architecture is only derived from the full kernel ID string, which for CentOS kernels contains the architecture information but not for Debian.  This means we should register a new field to the LS containing the architecture and calling `uname -m` to get it.

**Comment by vvidic** [comment]
On Mon, May 22, 2017 at 12:07:21PM -0700, Antoine Delvaux wrote:
> These look like Debian/Ubuntu kernel suffixes and are most probably due to bad parsing of the `uname` output or something similar.  We should double check that.

Right, we should not try to parse the kernel version but rather call:

$ uname --machine
x86_64

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by mfeit-internet2** [comment]
Use `uname -m` instead.  The long-form switch isn't POSIX.

**Comment by vvidic** [comment]
It seems the [sls_report](https://github.com/esnet/simple-lookup-service/blob/master/lookup/simple-lookup-service-client-python/clients/sls_report) script is trying to use the kernel version after the last dot as the architecture:
```
arch = kernel[0].split('.')[-1]
```
This works for RHEL kernels:
```
3.10.0-327.36.3.el7.x86_64
```
but not for Debian:
```
4.9.0-2-amd64
```
We should return the architecture as a separete parameter in LS registration.

**Comment by vvidic** [comment]
Created two pull requests for this issue: 
- #43
- perfsonar/perl-shared#35

Please review.

**Comment by vvidic** [comment]
Pull request for the report script is here: https://github.com/esnet/simple-lookup-service/pull/26

**Comment by arlake228** [comment]
Merged pull requests, closing.
