### ISSUE TITLE
Tag interfaces with pscheduler test types supported

### ISSUE THREAD

**Issue by arlake228** [perfsonar/ls-registration-daemon#46]
People need a way to flag an interface as the one to use for throughput vs the one to use for latency, especially since BWCTL is going away and people incorrectly have used it to mean "throughput" for years. We should give them a correct way such as add a "pscheduler-supported-test-types" or similar on interface records.

**Comment by igarny** [comment]
Hi Andy
This is of high importance to the GEANT project for the ability to fully and properly register its hosts in LHC projects and future pSconfig GUI.

Thanks

**Comment by igarny** [comment]
Hi Andy,

Thanks for your solution, I see it has great potential and allows for great flexibility. Still...I feel something is missing. Here you'll find 2 examples. 
From the examples my take is that the tools are being registered with the service, not with the interface registration.

example for interface registration: 
```
// 20180516095949
// http://ps-east.es.net:8090/lookup/interface/876de4b2-b015-4dda-8794-a958e8a927a5
{
  "expires": "2018-05-16T09:23:28.331Z",
  "interface-capacity": [
    "10000000000"
  ],
  "interface-name": [
    "p1p1"
  ],
  "client-uuid": [
    "a077261e-1e27-4483-8e01-d482faddb445"
  ],
  "interface-addresses": [
    "62.40.106.83",
    "2001:798:bb:2::6"
  ],
  "interface-mtu": [
    "9000"
  ],
  "interface-mac": [
    "90:e2:ba:6f:0f:1c"
  ],
  "state": "renewed",
  "type": [
    "interface"
  ],
  "uri": "lookup/interface/876de4b2-b015-4dda-8794-a958e8a927a5",
  "ttl": [
    
  ]
}
```
 
example for pscheduler service registration:
```
// 20180516100722
// http://ps-east.es.net:8090/lookup/service/2c7a26c3-88b8-4882-ac43-059d381cc1b3

{
  "location-state": [
    "Hessen"
  ],
  "location-city": [
    "Frankfurt"
  ],
  "expires": "2018-05-16T09:23:29.829Z",
  "pscheduler-tools": [
    "dnspy",
    "iperf2",
    "iperf3",
    "nuttcp",
    "owping",
    "paris-traceroute",
    "ping",
    "powstream",
    "psclock",
    "simplestreamer",
    "sleep",
    "sleepbgm",
    "snooze",
    "tracepath",
    "traceroute"
  ],
  "service-type": [
    "pscheduler"
  ],
  "service-version": [
    "pscheduler-1.0"
  ],
  "group-communities": [
    "GEANT"
  ],
  "type": [
    "service"
  ],
  "uri": "lookup/service/2c7a26c3-88b8-4882-ac43-059d381cc1b3",
  "service-host": [
    "lookup/host/dcce0a76-a148-4585-ad55-88ce13e855a7"
  ],
  "service-name": [
    "GNT-MP-u Frankfurt pScheduler"
  ],
```

**Comment by arlake228** [comment]
Can you explain to me why you think you need tools other than “I see it in
the service record”? The main use case is to determine what types of tests
are allowed on an interface. In general, we can leave it to pscheduler to
determine the best tool. The reason I am hesitant to do this is because the
average user is going to have no idea what tools go with which test, thus
it would make configuration more complicated. While possible, it’s also
more complicated to walk through each tool and match it with each test for
what seems relatively little benefit at the moment.


On May 16, 2018 at 4:15:40 AM, Ivan Garnizov (notifications@github.com)
wrote:

Hi Andy,

Thanks for your solution, I see it has great potential and allows for great
flexibility. Still...I feel something is missing. Here you'll find 2
examples.
From the examples my take is that the tools are being registered with the
service, not with the interface registration.

example for interface registration:

// 20180516095949
// http://ps-east.es.net:8090/lookup/interface/876de4b2-b015-4dda-8794-a958e8a927a5
{
  "expires": "2018-05-16T09:23:28.331Z",
  "interface-capacity": [
    "10000000000"
  ],
  "interface-name": [
    "p1p1"
  ],
  "client-uuid": [
    "a077261e-1e27-4483-8e01-d482faddb445"
  ],
  "interface-addresses": [
    "62.40.106.83",
    "2001:798:bb:2::6"
  ],
  "interface-mtu": [
    "9000"
  ],
  "interface-mac": [
    "90:e2:ba:6f:0f:1c"
  ],
  "state": "renewed",
  "type": [
    "interface"
  ],
  "uri": "lookup/interface/876de4b2-b015-4dda-8794-a958e8a927a5",
  "ttl": [

  ]
}

example for pscheduler service registration:

// 20180516100722
// http://ps-east.es.net:8090/lookup/service/2c7a26c3-88b8-4882-ac43-059d381cc1b3

{
  "location-state": [
    "Hessen"
  ],
  "location-city": [
    "Frankfurt"
  ],
  "expires": "2018-05-16T09:23:29.829Z",
  "pscheduler-tools": [
    "dnspy",
    "iperf2",
    "iperf3",
    "nuttcp",
    "owping",
    "paris-traceroute",
    "ping",
    "powstream",
    "psclock",
    "simplestreamer",
    "sleep",
    "sleepbgm",
    "snooze",
    "tracepath",
    "traceroute"
  ],
  "service-type": [
    "pscheduler"
  ],
  "service-version": [
    "pscheduler-1.0"
  ],
  "group-communities": [
    "GEANT"
  ],
  "type": [
    "service"
  ],
  "uri": "lookup/service/2c7a26c3-88b8-4882-ac43-059d381cc1b3",
  "service-host": [
    "lookup/host/dcce0a76-a148-4585-ad55-88ce13e855a7"
  ],
  "service-name": [
    "GNT-MP-u Frankfurt pScheduler"
  ],

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/ls-registration-daemon/issues/46#issuecomment-389434895>,
or mute the thread

**Comment by igarny** [comment]
The conclusion we came on the pS Dev call is:
Applications, which build test server lists for GUI management of tests should be consulting with the test assignments from "interface" registrations. It makes little to no sense on constructing lists of test participants based on service registrations.
