### ISSUE TITLE
Log output with record ID

### ISSUE THREAD

**Issue by tonin** [perfsonar/ls-registration-daemon#5]
It would be nice to have the record ID in the log output of the ls_registration_daemon for each service that get registered to the sLS.  At the moment, it only shows in case of duplicated record ID, but when troubleshooting a registration details, it is interesting to know the record ID so to look it up in the sLS directly.

Also, on some log lines, the information is put together without spaces, making it hard to read.  Examples:

```2015/06/09 13:31:10 (8535) INFO> Base.pm:479 perfSONAR_PS::LSRegistrationDaemon::Base::build_checksum - Checksum prior to md5 is service::http://tk4-1.ps.delvaux.net:8090/services/MP/OWAMP,https://tk4-1.ps.delvaux.net/services/MP/OWAMPmp-owampGEANT OWAMP Measurement Pointoppd-3.4lookup/person/cdbd91d5-1c16-4aa2-9edb-04e282f1f031GEANTDakarDakarSN123001010```

**Comment by igarny** [comment]
Hi guys,
I also support this call in the light of easier service support, since now I am forced to parse through the records based on more general criteria, which complicates the work needlessly.
