### ISSUE TITLE
lsregistrationdaemon breaks when selinux is enforced

### ISSUE THREAD

**Issue by rhclopes** [perfsonar/ls-registration-daemon#67]
perfsonar-lsregistrationdaemon.service fails to start when SELINUX is enforced.

Please see attached file.

Regards,
Raul
[lsregistration.txt](https://github.com/perfsonar/ls-dashboard/files/14013768/lsregistration.txt)

**Comment by arlake228** [comment]
Hey @rhclopes, thanks for this reports. A couple questions:

- What OS are you one?
-  Can you send me the results of `ausearch -m avc`? That will tell us specifically what selinux is blocking.

**Comment by rhclopes** [comment]
Hi Andy,

This is Alma 9.

The requested log is attached/
[ausearch.log](https://github.com/perfsonar/ls-registration-daemon/files/14039823/ausearch.log)

**Comment by rhclopes** [comment]
Hi,

The system is running perfsonar 5.0.7-1. It was installed with selinux Enforcing. I always do that.

I have just done  ''dnf reinstall perfsonar-lsregistrationdaemon".

Unfunny...

**Comment by arlake228** [comment]
This will be included in 5.1.0. In addition to any LS reg complaints, went through and cleaned-up policy surrounding any other complaints in audit.log.
