### ISSUE TITLE
ls_registration does not recognize the state of the OPPD service properly

### ISSUE THREAD

**Issue by igarny** [perfsonar/ls-registration-daemon#9]
configuration:
    <service>
        url_path   /services/MP/BWCTL
        inherits   local_bandwidth_service
        type   mp_bwctl
        service_version   oppd-3.4
        http_port   8090
    </service>
    <service>
        url_path   /services/MP/OWAMP
        inherits   local_latency_service
        type   mp_owamp
        service_version   oppd-3.4
        http_port   8090
    </service>

logs:

2015/07/21 07:48:37 (59805) INFO> Base.pm:255 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record 'GNT-MP Dublin-2 Measurement Archive
' is up, refreshing registration
2015/07/21 07:48:38 (59805) INFO> Base.pm:267 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record 'GNT-MP Dublin-2 BWCTL Measurement P
oint' is down
2015/07/21 07:48:38 (59805) INFO> Base.pm:267 perfSONAR_PS::LSRegistrationDaemon::Base::refresh - Record 'GNT-MP Dublin-2 OWAMP Measurement P
oint' is down

$ sudo  lsof -i | grep oppd
oppd.pl   13941    perfsonar    5u  IPv4   56376      0t0  TCP *:8090 (LISTEN)

Seems the ls_registration_daemon is not correctly identifying the state of the service.

**Comment by tonin** [comment]
This might be solved with https://github.com/perfsonar/ls-registration-daemon/commit/c13bdeb ; TBC.

**Comment by arlake228** [comment]
Sadly I don't think it does (haven't tested yet tho). It looks like oppd was already before the LSRegistrationDaemon in the boot order, even before this change.

**Comment by igarny** [comment]
Well. I would say the problem is not only in the boot order. The issue is experienced even on later LS daemon checks.
It would be kind of somewhat acceptable to have a delay in bwctl-mp and owamp-mp LS registrations, but it does not detect the service even on later checks and even on ls_registration_daemon service restarts.

**Comment by arlake228** [comment]
Testing locally on both a 3.4.2 VM and 3.5 VM, each with two interfaces and with Ivan's ls_registration_daemon.conf exactly I could not recreate the issue. Ivan suspects the Microsoft Hypervisor they are using may be at fault. They are already in the process of transitioning to something else and will try it on a different virtualization environment. We decided to close this and will re-open if problem persists in future.
